version: "3.8"

services:
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8787"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./packages/server:/app
    working_dir: /app
